移动行为:

  冲刺:
    开启: true
    # 控制冲刺的距离, 支持小数
    行动强度: 1.0

    # 消耗的体力值
    所需体力: 5

    # 检测允许冲刺的物品

    允许冲刺物品:
      # 检测 id, 手持以下物品可以冲刺, 默认为剑, 斧, 镐
      id:
        - "SWORD"
        - "AXE"
        - "PICKAXE"
      # 检测手持物品的 name
      name:
        - "(可冲刺)"
      # 检测手持物品的 lore
      lore:
        - "右键冲刺"

  二段跳:
    开启: true
    # 控制二段跳的高度
    行动强度: 0.5
    # 控制二段跳时玩家往前跳的力度
    冲刺力度: 1.0
    # 消耗的体力值
    所需体力: 10
    # 开启摔落伤害
    摔落伤害: true

体力恢复设置:
  # 当玩家停止消耗体力多长时间时开始恢复体力? 1000 毫秒 = 1 秒, 现在是 1.5 秒
  恢复间隔: 2000
  # 每 2tick 恢复一次体力值值(最低为1, 越低恢复越快, 越高越慢)
  恢复速度: 2
  # 每次恢复 1 体力
  恢复数量: 1


体力上限设置:
  # 默认体力值 15, 默认玩家拥有的体力值
  default: 15
  # vip1 体力值, 权限 sakuramove.stamina.vip1
  vip1: 20
  # vip2 体力值, 权限 sakuramove.stamina.vip2
  vip2: 25
  # svp 体力值, 权限 sakuramove.stamina.svp
  svp: 35

体力展示设置:

  ActionBar:
    开启: true
    体力槽样式: "█"
    空体力槽颜色代码: "&7"
    体力槽颜色代码: "&a"

Message:
  Reload: "&9&lSakuraMove &6&l>> &a插件已重载"