name: SakuraMove
main: com.entiv.${name}.Main
version: ${version}
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - Essentials
  - CMI

commands:
  SakuraMove:
    description: "description"
